apiVersion: v1
kind: Service
metadata:
  name: stored-files-service
  labels:
    app: stored-files-service
spec:
  selector:
    app: stored-files-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
